name: Python package
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Print versions
        run: |
          python --version
          which aws
          aws --version
      - name: Git status
        run: |
          git status
      - name: Print versions
        run: |
          ./hack/get-help.sh
      - name: Git status
        run: |
          git status
